# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # compiles all necessary source files
    gcc -c -g color.c
    gcc -c -g display.c -lm
    gcc -c -g animate.c
    gcc -c -g main.c
  displayName: 'Compile'

- script: |
    # combines them to package
    gcc -o C-Display main.o display.o animate.o color.o -lm 

    # removes all .o files
    rm main.o display.o animate.o color.o
  displayName: 'Combine'

- script: |
    # runs the package
    ls
    ./C-Display
  displayName: 'Run'
